sudo: required
services: 
  - docker

before_install:
    - docker build -t danbo-git/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true danbo-git/docker-react yarn test

deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "danboDocker-React"
  env: "DanbodockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-138438726154"
  bucket_path: "DanbodockerReact-env"  # Defaults to env name when newly created; Aka App
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
